import { NodeTypeDefinition } from './types';

export const NODE_DEFINITIONS: Record<string, NodeTypeDefinition> = {
  // TRIGGERS
  'trigger-manual': {
    type: 'trigger-manual',
    category: 'trigger',
    label: 'Manual Trigger',
    description: 'Start workflow manually with a button click',
    icon: '▶️',
    color: '#10b981',
    inputs: 0,
    outputs: 1,
    defaultConfig: {
      buttonLabel: 'Start Workflow',
      requireConfirmation: false,
    },
    configSchema: [
      {
        key: 'buttonLabel',
        label: 'Button Label',
        type: 'text',
        default: 'Start Workflow',
        placeholder: 'Enter button label',
      },
      {
        key: 'requireConfirmation',
        label: 'Require Confirmation',
        type: 'boolean',
        default: false,
      },
    ],
  },
  'trigger-schedule': {
    type: 'trigger-schedule',
    category: 'trigger',
    label: 'Schedule',
    description: 'Run workflow on a schedule using cron expressions',
    icon: '⏰',
    color: '#10b981',
    inputs: 0,
    outputs: 1,
    defaultConfig: {
      cron: '0 9 * * *',
      timezone: 'UTC',
      enabled: true,
    },
    configSchema: [
      {
        key: 'cron',
        label: 'Cron Expression',
        type: 'cron',
        required: true,
        default: '0 9 * * *',
        description: 'Enter a valid cron expression',
      },
      {
        key: 'timezone',
        label: 'Timezone',
        type: 'select',
        default: 'UTC',
        options: [
          { label: 'UTC', value: 'UTC' },
          { label: 'America/New_York', value: 'America/New_York' },
          { label: 'America/Los_Angeles', value: 'America/Los_Angeles' },
          { label: 'Europe/London', value: 'Europe/London' },
          { label: 'Asia/Tokyo', value: 'Asia/Tokyo' },
        ],
      },
      {
        key: 'enabled',
        label: 'Enabled',
        type: 'boolean',
        default: true,
      },
    ],
  },
  'trigger-webhook': {
    type: 'trigger-webhook',
    category: 'trigger',
    label: 'Webhook',
    description: 'Trigger workflow via HTTP webhook',
    icon: '🔗',
    color: '#10b981',
    inputs: 0,
    outputs: 1,
    defaultConfig: {
      method: 'POST',
      authType: 'none',
      responseType: 'json',
    },
    configSchema: [
      {
        key: 'method',
        label: 'HTTP Method',
        type: 'select',
        default: 'POST',
        options: [
          { label: 'GET', value: 'GET' },
          { label: 'POST', value: 'POST' },
          { label: 'PUT', value: 'PUT' },
          { label: 'PATCH', value: 'PATCH' },
        ],
      },
      {
        key: 'authType',
        label: 'Authentication',
        type: 'select',
        default: 'none',
        options: [
          { label: 'None', value: 'none' },
          { label: 'API Key', value: 'apiKey' },
          { label: 'Bearer Token', value: 'bearer' },
          { label: 'Basic Auth', value: 'basic' },
        ],
      },
      {
        key: 'responseType',
        label: 'Response Type',
        type: 'select',
        default: 'json',
        options: [
          { label: 'JSON', value: 'json' },
          { label: 'Text', value: 'text' },
        ],
      },
    ],
  },
  'trigger-file-upload': {
    type: 'trigger-file-upload',
    category: 'trigger',
    label: 'File Upload',
    description: 'Trigger when a file is uploaded',
    icon: '📁',
    color: '#10b981',
    inputs: 0,
    outputs: 1,
    defaultConfig: {
      allowedTypes: [],
      maxSize: 10,
    },
    configSchema: [
      {
        key: 'allowedTypes',
        label: 'Allowed File Types',
        type: 'text',
        placeholder: 'e.g., .pdf, .csv, .xlsx',
        description: 'Comma-separated list of file extensions',
      },
      {
        key: 'maxSize',
        label: 'Max File Size (MB)',
        type: 'number',
        default: 10,
        validation: { min: 1, max: 100 },
      },
    ],
  },
  'trigger-email-received': {
    type: 'trigger-email-received',
    category: 'trigger',
    label: 'Email Received',
    description: 'Trigger when an email is received',
    icon: '📧',
    color: '#10b981',
    inputs: 0,
    outputs: 1,
    defaultConfig: {
      emailAddress: '',
      filters: {},
    },
    configSchema: [
      {
        key: 'emailAddress',
        label: 'Email Address',
        type: 'text',
        required: true,
        placeholder: 'workflow@example.com',
      },
      {
        key: 'subjectFilter',
        label: 'Subject Filter (optional)',
        type: 'text',
        placeholder: 'Filter by subject keywords',
      },
    ],
  },

  // ACTIONS
  'action-http-request': {
    type: 'action-http-request',
    category: 'action',
    label: 'HTTP Request',
    description: 'Make HTTP API requests',
    icon: '🌐',
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
    defaultConfig: {
      method: 'GET',
      url: '',
      headers: {},
      body: {},
    },
    configSchema: [
      {
        key: 'method',
        label: 'Method',
        type: 'select',
        default: 'GET',
        required: true,
        options: [
          { label: 'GET', value: 'GET' },
          { label: 'POST', value: 'POST' },
          { label: 'PUT', value: 'PUT' },
          { label: 'PATCH', value: 'PATCH' },
          { label: 'DELETE', value: 'DELETE' },
        ],
      },
      {
        key: 'url',
        label: 'URL',
        type: 'text',
        required: true,
        placeholder: 'https://api.example.com/endpoint',
      },
      {
        key: 'headers',
        label: 'Headers',
        type: 'json',
        default: {},
        placeholder: '{"Content-Type": "application/json"}',
      },
      {
        key: 'body',
        label: 'Body',
        type: 'json',
        default: {},
        placeholder: '{"key": "value"}',
      },
    ],
  },
  'action-database-query': {
    type: 'action-database-query',
    category: 'action',
    label: 'Database Query',
    description: 'Query database with SQL',
    icon: '🗄️',
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
    defaultConfig: {
      operation: 'select',
      query: '',
    },
    configSchema: [
      {
        key: 'operation',
        label: 'Operation',
        type: 'select',
        default: 'select',
        options: [
          { label: 'SELECT', value: 'select' },
          { label: 'INSERT', value: 'insert' },
          { label: 'UPDATE', value: 'update' },
          { label: 'DELETE', value: 'delete' },
        ],
      },
      {
        key: 'query',
        label: 'SQL Query',
        type: 'code',
        required: true,
        placeholder: 'SELECT * FROM users WHERE id = $1',
      },
      {
        key: 'parameters',
        label: 'Parameters',
        type: 'json',
        default: [],
        placeholder: '["value1", "value2"]',
      },
    ],
  },
  'action-ai-generation': {
    type: 'action-ai-generation',
    category: 'action',
    label: 'AI Generation',
    description: 'Generate content using AI',
    icon: '🤖',
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
    defaultConfig: {
      model: 'gpt-4',
      prompt: '',
      temperature: 0.7,
    },
    configSchema: [
      {
        key: 'model',
        label: 'Model',
        type: 'select',
        default: 'gpt-4',
        options: [
          { label: 'GPT-4', value: 'gpt-4' },
          { label: 'GPT-3.5 Turbo', value: 'gpt-3.5-turbo' },
          { label: 'Claude 3', value: 'claude-3' },
        ],
      },
      {
        key: 'prompt',
        label: 'Prompt',
        type: 'textarea',
        required: true,
        placeholder: 'Enter your prompt here...',
      },
      {
        key: 'temperature',
        label: 'Temperature',
        type: 'number',
        default: 0.7,
        validation: { min: 0, max: 2 },
      },
    ],
  },
  'action-send-email': {
    type: 'action-send-email',
    category: 'action',
    label: 'Send Email',
    description: 'Send email notifications',
    icon: '✉️',
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
    defaultConfig: {
      to: '',
      subject: '',
      body: '',
    },
    configSchema: [
      {
        key: 'to',
        label: 'To',
        type: 'text',
        required: true,
        placeholder: 'recipient@example.com',
      },
      {
        key: 'subject',
        label: 'Subject',
        type: 'text',
        required: true,
        placeholder: 'Email subject',
      },
      {
        key: 'body',
        label: 'Body',
        type: 'textarea',
        required: true,
        placeholder: 'Email content...',
      },
      {
        key: 'cc',
        label: 'CC (optional)',
        type: 'text',
        placeholder: 'cc@example.com',
      },
    ],
  },
  'action-file-operation': {
    type: 'action-file-operation',
    category: 'action',
    label: 'File Operation',
    description: 'Read, write, or transform files',
    icon: '📄',
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
    defaultConfig: {
      operation: 'read',
      path: '',
    },
    configSchema: [
      {
        key: 'operation',
        label: 'Operation',
        type: 'select',
        default: 'read',
        options: [
          { label: 'Read', value: 'read' },
          { label: 'Write', value: 'write' },
          { label: 'Delete', value: 'delete' },
          { label: 'Convert', value: 'convert' },
        ],
      },
      {
        key: 'path',
        label: 'File Path',
        type: 'text',
        required: true,
        placeholder: '/path/to/file.txt',
      },
      {
        key: 'content',
        label: 'Content (for write)',
        type: 'textarea',
        placeholder: 'File content...',
      },
    ],
  },

  // LOGIC
  'logic-condition': {
    type: 'logic-condition',
    category: 'logic',
    label: 'Condition',
    description: 'If/else branching logic',
    icon: '🔀',
    color: '#f59e0b',
    inputs: 1,
    outputs: 2,
    defaultConfig: {
      operator: 'equals',
      value1: '',
      value2: '',
    },
    configSchema: [
      {
        key: 'operator',
        label: 'Operator',
        type: 'select',
        default: 'equals',
        options: [
          { label: 'Equals', value: 'equals' },
          { label: 'Not Equals', value: 'notEquals' },
          { label: 'Greater Than', value: 'greaterThan' },
          { label: 'Less Than', value: 'lessThan' },
          { label: 'Contains', value: 'contains' },
          { label: 'Is Empty', value: 'isEmpty' },
        ],
      },
      {
        key: 'value1',
        label: 'Value 1',
        type: 'variables',
        required: true,
        placeholder: 'First value to compare',
      },
      {
        key: 'value2',
        label: 'Value 2',
        type: 'variables',
        placeholder: 'Second value to compare',
      },
    ],
  },
  'logic-loop': {
    type: 'logic-loop',
    category: 'logic',
    label: 'Loop',
    description: 'Iterate over arrays or objects',
    icon: '🔄',
    color: '#f59e0b',
    inputs: 1,
    outputs: 1,
    defaultConfig: {
      items: [],
      maxIterations: 100,
    },
    configSchema: [
      {
        key: 'items',
        label: 'Items to Loop',
        type: 'variables',
        required: true,
        description: 'Array or object to iterate over',
      },
      {
        key: 'maxIterations',
        label: 'Max Iterations',
        type: 'number',
        default: 100,
        validation: { min: 1, max: 1000 },
      },
    ],
  },
  'logic-switch': {
    type: 'logic-switch',
    category: 'logic',
    label: 'Switch',
    description: 'Multi-way branching',
    icon: '🔀',
    color: '#f59e0b',
    inputs: 1,
    outputs: 4,
    defaultConfig: {
      value: '',
      cases: [],
    },
    configSchema: [
      {
        key: 'value',
        label: 'Switch Value',
        type: 'variables',
        required: true,
        placeholder: 'Value to switch on',
      },
      {
        key: 'cases',
        label: 'Cases',
        type: 'json',
        default: [],
        placeholder: '[{"case": "value1", "output": 0}, {"case": "value2", "output": 1}]',
      },
    ],
  },
  'logic-delay': {
    type: 'logic-delay',
    category: 'logic',
    label: 'Delay',
    description: 'Wait before continuing',
    icon: '⏸️',
    color: '#f59e0b',
    inputs: 1,
    outputs: 1,
    defaultConfig: {
      duration: 1000,
      unit: 'milliseconds',
    },
    configSchema: [
      {
        key: 'duration',
        label: 'Duration',
        type: 'number',
        required: true,
        default: 1000,
      },
      {
        key: 'unit',
        label: 'Unit',
        type: 'select',
        default: 'milliseconds',
        options: [
          { label: 'Milliseconds', value: 'milliseconds' },
          { label: 'Seconds', value: 'seconds' },
          { label: 'Minutes', value: 'minutes' },
        ],
      },
    ],
  },
  'logic-stop': {
    type: 'logic-stop',
    category: 'logic',
    label: 'Stop',
    description: 'Stop workflow execution',
    icon: '⏹️',
    color: '#f59e0b',
    inputs: 1,
    outputs: 0,
    defaultConfig: {
      message: 'Workflow stopped',
    },
    configSchema: [
      {
        key: 'message',
        label: 'Stop Message',
        type: 'text',
        default: 'Workflow stopped',
        placeholder: 'Optional stop message',
      },
    ],
  },

  // DATA
  'data-transform': {
    type: 'data-transform',
    category: 'data',
    label: 'Transform',
    description: 'Transform and map data',
    icon: '🔧',
    color: '#8b5cf6',
    inputs: 1,
    outputs: 1,
    defaultConfig: {
      transformations: [],
    },
    configSchema: [
      {
        key: 'transformations',
        label: 'Transformations',
        type: 'json',
        required: true,
        placeholder: '{"newField": "{{oldField}}", "uppercase": "{{field.toUpperCase()}}"}',
      },
    ],
  },
  'data-filter': {
    type: 'data-filter',
    category: 'data',
    label: 'Filter',
    description: 'Filter arrays based on conditions',
    icon: '🔍',
    color: '#8b5cf6',
    inputs: 1,
    outputs: 1,
    defaultConfig: {
      condition: '',
    },
    configSchema: [
      {
        key: 'array',
        label: 'Array to Filter',
        type: 'variables',
        required: true,
      },
      {
        key: 'condition',
        label: 'Filter Condition',
        type: 'code',
        required: true,
        placeholder: 'item.value > 10',
      },
    ],
  },
  'data-merge': {
    type: 'data-merge',
    category: 'data',
    label: 'Merge',
    description: 'Merge multiple data sources',
    icon: '🔗',
    color: '#8b5cf6',
    inputs: 2,
    outputs: 1,
    defaultConfig: {
      strategy: 'concat',
    },
    configSchema: [
      {
        key: 'strategy',
        label: 'Merge Strategy',
        type: 'select',
        default: 'concat',
        options: [
          { label: 'Concatenate Arrays', value: 'concat' },
          { label: 'Merge Objects', value: 'merge' },
          { label: 'Deep Merge', value: 'deepMerge' },
        ],
      },
    ],
  },
  'data-split': {
    type: 'data-split',
    category: 'data',
    label: 'Split',
    description: 'Split data into multiple outputs',
    icon: '✂️',
    color: '#8b5cf6',
    inputs: 1,
    outputs: 2,
    defaultConfig: {
      splitBy: 'property',
    },
    configSchema: [
      {
        key: 'splitBy',
        label: 'Split By',
        type: 'select',
        default: 'property',
        options: [
          { label: 'Property Value', value: 'property' },
          { label: 'Array Chunks', value: 'chunks' },
          { label: 'Condition', value: 'condition' },
        ],
      },
      {
        key: 'value',
        label: 'Split Value',
        type: 'text',
        required: true,
        placeholder: 'Property name or chunk size',
      },
    ],
  },
  'data-aggregate': {
    type: 'data-aggregate',
    category: 'data',
    label: 'Aggregate',
    description: 'Aggregate and summarize data',
    icon: '📊',
    color: '#8b5cf6',
    inputs: 1,
    outputs: 1,
    defaultConfig: {
      operation: 'sum',
    },
    configSchema: [
      {
        key: 'operation',
        label: 'Operation',
        type: 'select',
        default: 'sum',
        options: [
          { label: 'Sum', value: 'sum' },
          { label: 'Average', value: 'average' },
          { label: 'Count', value: 'count' },
          { label: 'Min', value: 'min' },
          { label: 'Max', value: 'max' },
        ],
      },
      {
        key: 'field',
        label: 'Field to Aggregate',
        type: 'text',
        required: true,
        placeholder: 'Field name',
      },
    ],
  },

  // INTEGRATIONS
  'integration-github': {
    type: 'integration-github',
    category: 'integration',
    label: 'GitHub',
    description: 'GitHub integration actions',
    icon: '🐙',
    color: '#ec4899',
    inputs: 1,
    outputs: 1,
    defaultConfig: {
      action: 'createIssue',
      repository: '',
    },
    configSchema: [
      {
        key: 'action',
        label: 'Action',
        type: 'select',
        default: 'createIssue',
        options: [
          { label: 'Create Issue', value: 'createIssue' },
          { label: 'Create PR', value: 'createPR' },
          { label: 'Add Comment', value: 'addComment' },
          { label: 'List Issues', value: 'listIssues' },
        ],
      },
      {
        key: 'repository',
        label: 'Repository',
        type: 'text',
        required: true,
        placeholder: 'owner/repo',
      },
    ],
  },
  'integration-slack': {
    type: 'integration-slack',
    category: 'integration',
    label: 'Slack',
    description: 'Send messages to Slack',
    icon: '💬',
    color: '#ec4899',
    inputs: 1,
    outputs: 1,
    defaultConfig: {
      action: 'sendMessage',
      channel: '',
      message: '',
    },
    configSchema: [
      {
        key: 'action',
        label: 'Action',
        type: 'select',
        default: 'sendMessage',
        options: [
          { label: 'Send Message', value: 'sendMessage' },
          { label: 'Send File', value: 'sendFile' },
          { label: 'Update Message', value: 'updateMessage' },
        ],
      },
      {
        key: 'channel',
        label: 'Channel',
        type: 'text',
        required: true,
        placeholder: '#general',
      },
      {
        key: 'message',
        label: 'Message',
        type: 'textarea',
        required: true,
        placeholder: 'Your message here...',
      },
    ],
  },
  'integration-discord': {
    type: 'integration-discord',
    category: 'integration',
    label: 'Discord',
    description: 'Send messages to Discord',
    icon: '🎮',
    color: '#ec4899',
    inputs: 1,
    outputs: 1,
    defaultConfig: {
      webhookUrl: '',
      content: '',
    },
    configSchema: [
      {
        key: 'webhookUrl',
        label: 'Webhook URL',
        type: 'text',
        required: true,
        placeholder: 'Discord webhook URL',
      },
      {
        key: 'content',
        label: 'Message Content',
        type: 'textarea',
        required: true,
        placeholder: 'Your message...',
      },
      {
        key: 'username',
        label: 'Username (optional)',
        type: 'text',
        placeholder: 'Bot name',
      },
    ],
  },
  'integration-stripe': {
    type: 'integration-stripe',
    category: 'integration',
    label: 'Stripe',
    description: 'Stripe payment operations',
    icon: '💳',
    color: '#ec4899',
    inputs: 1,
    outputs: 1,
    defaultConfig: {
      action: 'createCustomer',
    },
    configSchema: [
      {
        key: 'action',
        label: 'Action',
        type: 'select',
        default: 'createCustomer',
        options: [
          { label: 'Create Customer', value: 'createCustomer' },
          { label: 'Create Payment Intent', value: 'createPaymentIntent' },
          { label: 'Create Subscription', value: 'createSubscription' },
          { label: 'Refund Payment', value: 'refundPayment' },
        ],
      },
    ],
  },
  'integration-sendgrid': {
    type: 'integration-sendgrid',
    category: 'integration',
    label: 'SendGrid',
    description: 'Send emails via SendGrid',
    icon: '📮',
    color: '#ec4899',
    inputs: 1,
    outputs: 1,
    defaultConfig: {
      to: '',
      subject: '',
      html: '',
    },
    configSchema: [
      {
        key: 'to',
        label: 'To',
        type: 'text',
        required: true,
        placeholder: 'recipient@example.com',
      },
      {
        key: 'subject',
        label: 'Subject',
        type: 'text',
        required: true,
        placeholder: 'Email subject',
      },
      {
        key: 'html',
        label: 'HTML Content',
        type: 'textarea',
        required: true,
        placeholder: '<p>Your HTML content...</p>',
      },
      {
        key: 'templateId',
        label: 'Template ID (optional)',
        type: 'text',
        placeholder: 'SendGrid template ID',
      },
    ],
  },
};

export const NODE_CATEGORIES = [
  { id: 'trigger', label: 'Triggers', color: '#10b981' },
  { id: 'action', label: 'Actions', color: '#3b82f6' },
  { id: 'logic', label: 'Logic', color: '#f59e0b' },
  { id: 'data', label: 'Data', color: '#8b5cf6' },
  { id: 'integration', label: 'Integrations', color: '#ec4899' },
];
