import { PlatformTheme } from './types'

export const themePresets: Record<string, PlatformTheme> = {
  'default-dark': {
    id: 'default-dark',
    name: 'Default Dark',
    typography: {
      titleFont: 'system-ui, sans-serif',
      titleSize: '1.875rem',
      titleWeight: '700',
      titleColor: '#ffffff',
      bodyFont: 'system-ui, sans-serif',
      bodySize: '0.875rem',
      bodyWeight: '400',
      bodyColor: '#e5e5e5',
      mutedColor: '#a3a3a3',
      lineHeight: '1.5',
    },
    colors: {
      primary: '#3b82f6',
      primaryHover: '#2563eb',
      secondary: '#6b7280',
      secondaryHover: '#4b5563',
      accent: '#8b5cf6',
      accentHover: '#7c3aed',
      danger: '#ef4444',
      dangerHover: '#dc2626',
      success: '#10b981',
      successHover: '#059669',
      warning: '#f59e0b',
      warningHover: '#d97706',
      info: '#06b6d4',
      infoHover: '#0891b2',
    },
    buttons: {
      borderRadius: '0.5rem',
      borderWidth: '1px',
      primaryBg: '#3b82f6',
      primaryText: '#ffffff',
      primaryBorder: 'transparent',
      primaryHoverBg: '#2563eb',
      secondaryBg: '#27272a',
      secondaryText: '#e5e5e5',
      secondaryBorder: '#3f3f46',
      secondaryHoverBg: '#3f3f46',
      fontSize: '0.875rem',
      fontWeight: '500',
    },
    cards: {
      background: '#18181b',
      border: '#27272a',
      borderRadius: '0.75rem',
      borderWidth: '1px',
      shadow: '0 1px 3px 0 rgb(0 0 0 / 0.1)',
      hoverShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)',
      padding: '1.5rem',
    },
    inputs: {
      background: '#18181b',
      border: '#27272a',
      borderRadius: '0.5rem',
      borderWidth: '1px',
      text: '#e5e5e5',
      placeholder: '#71717a',
      focusBorder: '#3b82f6',
      focusShadow: '0 0 0 3px rgba(59, 130, 246, 0.1)',
    },
    badges: {
      borderRadius: '0.375rem',
      fontSize: '0.75rem',
      fontWeight: '500',
      padding: '0.25rem 0.5rem',
    },
    navigation: {
      background: '#18181b',
      border: '#27272a',
      itemColor: '#a1a1aa',
      itemHoverBg: '#27272a',
      itemActiveBg: '#3b82f6',
      itemActiveColor: '#ffffff',
    },
    layout: {
      pageBackground: '#0a0a0a',
      containerMaxWidth: '80rem',
      borderRadius: '0.5rem',
      spacing: '1.5rem',
    },
  },

  'light': {
    id: 'light',
    name: 'Light Mode',
    typography: {
      titleFont: 'system-ui, sans-serif',
      titleSize: '1.875rem',
      titleWeight: '700',
      titleColor: '#0a0a0a',
      bodyFont: 'system-ui, sans-serif',
      bodySize: '0.875rem',
      bodyWeight: '400',
      bodyColor: '#404040',
      mutedColor: '#737373',
      lineHeight: '1.5',
    },
    colors: {
      primary: '#3b82f6',
      primaryHover: '#2563eb',
      secondary: '#71717a',
      secondaryHover: '#52525b',
      accent: '#8b5cf6',
      accentHover: '#7c3aed',
      danger: '#ef4444',
      dangerHover: '#dc2626',
      success: '#10b981',
      successHover: '#059669',
      warning: '#f59e0b',
      warningHover: '#d97706',
      info: '#06b6d4',
      infoHover: '#0891b2',
    },
    buttons: {
      borderRadius: '0.5rem',
      borderWidth: '1px',
      primaryBg: '#3b82f6',
      primaryText: '#ffffff',
      primaryBorder: 'transparent',
      primaryHoverBg: '#2563eb',
      secondaryBg: '#f4f4f5',
      secondaryText: '#18181b',
      secondaryBorder: '#e4e4e7',
      secondaryHoverBg: '#e4e4e7',
      fontSize: '0.875rem',
      fontWeight: '500',
    },
    cards: {
      background: '#ffffff',
      border: '#e4e4e7',
      borderRadius: '0.75rem',
      borderWidth: '1px',
      shadow: '0 1px 3px 0 rgb(0 0 0 / 0.1)',
      hoverShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)',
      padding: '1.5rem',
    },
    inputs: {
      background: '#ffffff',
      border: '#d4d4d8',
      borderRadius: '0.5rem',
      borderWidth: '1px',
      text: '#18181b',
      placeholder: '#a1a1aa',
      focusBorder: '#3b82f6',
      focusShadow: '0 0 0 3px rgba(59, 130, 246, 0.1)',
    },
    badges: {
      borderRadius: '0.375rem',
      fontSize: '0.75rem',
      fontWeight: '500',
      padding: '0.25rem 0.5rem',
    },
    navigation: {
      background: '#ffffff',
      border: '#e4e4e7',
      itemColor: '#71717a',
      itemHoverBg: '#f4f4f5',
      itemActiveBg: '#3b82f6',
      itemActiveColor: '#ffffff',
    },
    layout: {
      pageBackground: '#fafafa',
      containerMaxWidth: '80rem',
      borderRadius: '0.5rem',
      spacing: '1.5rem',
    },
  },

  'high-contrast': {
    id: 'high-contrast',
    name: 'High Contrast',
    typography: {
      titleFont: 'system-ui, sans-serif',
      titleSize: '1.875rem',
      titleWeight: '900',
      titleColor: '#ffffff',
      bodyFont: 'system-ui, sans-serif',
      bodySize: '1rem',
      bodyWeight: '500',
      bodyColor: '#ffffff',
      mutedColor: '#d4d4d8',
      lineHeight: '1.7',
    },
    colors: {
      primary: '#60a5fa',
      primaryHover: '#3b82f6',
      secondary: '#a1a1aa',
      secondaryHover: '#71717a',
      accent: '#c084fc',
      accentHover: '#a855f7',
      danger: '#f87171',
      dangerHover: '#ef4444',
      success: '#34d399',
      successHover: '#10b981',
      warning: '#fbbf24',
      warningHover: '#f59e0b',
      info: '#22d3ee',
      infoHover: '#06b6d4',
    },
    buttons: {
      borderRadius: '0.375rem',
      borderWidth: '3px',
      primaryBg: '#60a5fa',
      primaryText: '#000000',
      primaryBorder: '#ffffff',
      primaryHoverBg: '#3b82f6',
      secondaryBg: '#000000',
      secondaryText: '#ffffff',
      secondaryBorder: '#ffffff',
      secondaryHoverBg: '#18181b',
      fontSize: '1rem',
      fontWeight: '700',
    },
    cards: {
      background: '#000000',
      border: '#ffffff',
      borderRadius: '0.5rem',
      borderWidth: '3px',
      shadow: 'none',
      hoverShadow: '0 0 0 4px rgba(255, 255, 255, 0.2)',
      padding: '2rem',
    },
    inputs: {
      background: '#000000',
      border: '#ffffff',
      borderRadius: '0.375rem',
      borderWidth: '2px',
      text: '#ffffff',
      placeholder: '#a1a1aa',
      focusBorder: '#60a5fa',
      focusShadow: '0 0 0 4px rgba(96, 165, 250, 0.5)',
    },
    badges: {
      borderRadius: '0.25rem',
      fontSize: '0.875rem',
      fontWeight: '700',
      padding: '0.375rem 0.75rem',
    },
    navigation: {
      background: '#000000',
      border: '#ffffff',
      itemColor: '#ffffff',
      itemHoverBg: '#18181b',
      itemActiveBg: '#60a5fa',
      itemActiveColor: '#000000',
    },
    layout: {
      pageBackground: '#000000',
      containerMaxWidth: '80rem',
      borderRadius: '0.375rem',
      spacing: '2rem',
    },
  },

  'cyberpunk': {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    typography: {
      titleFont: '"Orbitron", "Rajdhani", system-ui, sans-serif',
      titleSize: '2rem',
      titleWeight: '800',
      titleColor: '#00ffff',
      bodyFont: 'system-ui, sans-serif',
      bodySize: '0.875rem',
      bodyWeight: '400',
      bodyColor: '#e0e0ff',
      mutedColor: '#a0a0d0',
      lineHeight: '1.6',
    },
    colors: {
      primary: '#ff00ff',
      primaryHover: '#cc00cc',
      secondary: '#00ffff',
      secondaryHover: '#00cccc',
      accent: '#ffff00',
      accentHover: '#cccc00',
      danger: '#ff0066',
      dangerHover: '#cc0052',
      success: '#00ff88',
      successHover: '#00cc6e',
      warning: '#ff9900',
      warningHover: '#cc7a00',
      info: '#00ccff',
      infoHover: '#00a3cc',
    },
    buttons: {
      borderRadius: '0rem',
      borderWidth: '2px',
      primaryBg: '#ff00ff',
      primaryText: '#000000',
      primaryBorder: '#00ffff',
      primaryHoverBg: '#cc00cc',
      secondaryBg: 'transparent',
      secondaryText: '#00ffff',
      secondaryBorder: '#00ffff',
      secondaryHoverBg: 'rgba(0, 255, 255, 0.1)',
      fontSize: '0.875rem',
      fontWeight: '700',
    },
    cards: {
      background: '#0a0015',
      border: '#ff00ff',
      borderRadius: '0rem',
      borderWidth: '2px',
      shadow: '0 0 20px rgba(255, 0, 255, 0.3)',
      hoverShadow: '0 0 30px rgba(255, 0, 255, 0.5)',
      padding: '1.5rem',
    },
    inputs: {
      background: '#0a0015',
      border: '#00ffff',
      borderRadius: '0rem',
      borderWidth: '2px',
      text: '#e0e0ff',
      placeholder: '#6060a0',
      focusBorder: '#ff00ff',
      focusShadow: '0 0 10px rgba(255, 0, 255, 0.5)',
    },
    badges: {
      borderRadius: '0rem',
      fontSize: '0.75rem',
      fontWeight: '700',
      padding: '0.25rem 0.75rem',
    },
    navigation: {
      background: '#0a0015',
      border: '#ff00ff',
      itemColor: '#00ffff',
      itemHoverBg: 'rgba(255, 0, 255, 0.2)',
      itemActiveBg: '#ff00ff',
      itemActiveColor: '#000000',
    },
    layout: {
      pageBackground: '#000010',
      containerMaxWidth: '80rem',
      borderRadius: '0rem',
      spacing: '1.5rem',
    },
  },

  'ocean': {
    id: 'ocean',
    name: 'Ocean Depths',
    typography: {
      titleFont: 'system-ui, sans-serif',
      titleSize: '1.875rem',
      titleWeight: '700',
      titleColor: '#e0f2fe',
      bodyFont: 'system-ui, sans-serif',
      bodySize: '0.875rem',
      bodyWeight: '400',
      bodyColor: '#bae6fd',
      mutedColor: '#7dd3fc',
      lineHeight: '1.6',
    },
    colors: {
      primary: '#0ea5e9',
      primaryHover: '#0284c7',
      secondary: '#06b6d4',
      secondaryHover: '#0891b2',
      accent: '#14b8a6',
      accentHover: '#0d9488',
      danger: '#f43f5e',
      dangerHover: '#e11d48',
      success: '#10b981',
      successHover: '#059669',
      warning: '#f59e0b',
      warningHover: '#d97706',
      info: '#06b6d4',
      infoHover: '#0891b2',
    },
    buttons: {
      borderRadius: '0.75rem',
      borderWidth: '1px',
      primaryBg: '#0ea5e9',
      primaryText: '#ffffff',
      primaryBorder: 'transparent',
      primaryHoverBg: '#0284c7',
      secondaryBg: '#164e63',
      secondaryText: '#bae6fd',
      secondaryBorder: '#0e7490',
      secondaryHoverBg: '#155e75',
      fontSize: '0.875rem',
      fontWeight: '500',
    },
    cards: {
      background: '#0c4a6e',
      border: '#075985',
      borderRadius: '1rem',
      borderWidth: '1px',
      shadow: '0 4px 6px -1px rgba(0, 0, 0, 0.3)',
      hoverShadow: '0 10px 15px -3px rgba(14, 165, 233, 0.3)',
      padding: '1.5rem',
    },
    inputs: {
      background: '#164e63',
      border: '#0e7490',
      borderRadius: '0.5rem',
      borderWidth: '1px',
      text: '#e0f2fe',
      placeholder: '#67e8f9',
      focusBorder: '#0ea5e9',
      focusShadow: '0 0 0 3px rgba(14, 165, 233, 0.2)',
    },
    badges: {
      borderRadius: '0.5rem',
      fontSize: '0.75rem',
      fontWeight: '500',
      padding: '0.25rem 0.5rem',
    },
    navigation: {
      background: '#0c4a6e',
      border: '#075985',
      itemColor: '#7dd3fc',
      itemHoverBg: '#164e63',
      itemActiveBg: '#0ea5e9',
      itemActiveColor: '#ffffff',
    },
    layout: {
      pageBackground: '#082f49',
      containerMaxWidth: '80rem',
      borderRadius: '0.5rem',
      spacing: '1.5rem',
    },
  },

  'forest': {
    id: 'forest',
    name: 'Forest Canopy',
    typography: {
      titleFont: 'system-ui, sans-serif',
      titleSize: '1.875rem',
      titleWeight: '700',
      titleColor: '#d9f99d',
      bodyFont: 'system-ui, sans-serif',
      bodySize: '0.875rem',
      bodyWeight: '400',
      bodyColor: '#d9f99d',
      mutedColor: '#a3e635',
      lineHeight: '1.6',
    },
    colors: {
      primary: '#84cc16',
      primaryHover: '#65a30d',
      secondary: '#22c55e',
      secondaryHover: '#16a34a',
      accent: '#eab308',
      accentHover: '#ca8a04',
      danger: '#f97316',
      dangerHover: '#ea580c',
      success: '#22c55e',
      successHover: '#16a34a',
      warning: '#eab308',
      warningHover: '#ca8a04',
      info: '#14b8a6',
      infoHover: '#0d9488',
    },
    buttons: {
      borderRadius: '0.625rem',
      borderWidth: '1px',
      primaryBg: '#84cc16',
      primaryText: '#1a2e05',
      primaryBorder: 'transparent',
      primaryHoverBg: '#65a30d',
      secondaryBg: '#365314',
      secondaryText: '#d9f99d',
      secondaryBorder: '#4d7c0f',
      secondaryHoverBg: '#3f6212',
      fontSize: '0.875rem',
      fontWeight: '500',
    },
    cards: {
      background: '#1a2e05',
      border: '#365314',
      borderRadius: '0.875rem',
      borderWidth: '1px',
      shadow: '0 4px 6px -1px rgba(0, 0, 0, 0.3)',
      hoverShadow: '0 10px 15px -3px rgba(132, 204, 22, 0.2)',
      padding: '1.5rem',
    },
    inputs: {
      background: '#1a2e05',
      border: '#4d7c0f',
      borderRadius: '0.5rem',
      borderWidth: '1px',
      text: '#d9f99d',
      placeholder: '#84cc16',
      focusBorder: '#84cc16',
      focusShadow: '0 0 0 3px rgba(132, 204, 22, 0.2)',
    },
    badges: {
      borderRadius: '0.5rem',
      fontSize: '0.75rem',
      fontWeight: '500',
      padding: '0.25rem 0.5rem',
    },
    navigation: {
      background: '#1a2e05',
      border: '#365314',
      itemColor: '#a3e635',
      itemHoverBg: '#365314',
      itemActiveBg: '#84cc16',
      itemActiveColor: '#1a2e05',
    },
    layout: {
      pageBackground: '#14120b',
      containerMaxWidth: '80rem',
      borderRadius: '0.5rem',
      spacing: '1.5rem',
    },
  },
}

export const getPresetNames = () => Object.keys(themePresets)

export const getPreset = (id: string): PlatformTheme | undefined => themePresets[id]

export const getAllPresets = (): PlatformTheme[] => Object.values(themePresets)
