import { PlatformTheme } from './types'

export const themePresets: Record<string, PlatformTheme> = {
  'minimal': {
    id: 'minimal',
    name: 'Minimal',
    typography: {
      titleFont: 'system-ui, -apple-system, sans-serif',
      titleSize: '1.75rem',
      titleWeight: '600',
      titleColor: '#1a1a1a',
      bodyFont: 'system-ui, -apple-system, sans-serif',
      bodySize: '0.9375rem',
      bodyWeight: '400',
      bodyColor: '#525252',
      mutedColor: '#a3a3a3',
      lineHeight: '1.65',
    },
    colors: {
      primary: '#000000',
      primaryHover: '#262626',
      secondary: '#f5f5f5',
      secondaryHover: '#e5e5e5',
      accent: '#3b82f6',
      accentHover: '#2563eb',
      danger: '#dc2626',
      dangerHover: '#b91c1c',
      success: '#16a34a',
      successHover: '#15803d',
      warning: '#ea580c',
      warningHover: '#c2410c',
      info: '#0891b2',
      infoHover: '#0e7490',
    },
    buttons: {
      borderRadius: '0.375rem',
      borderWidth: '1px',
      primaryBg: '#000000',
      primaryText: '#ffffff',
      primaryBorder: 'transparent',
      primaryHoverBg: '#262626',
      secondaryBg: '#ffffff',
      secondaryText: '#1a1a1a',
      secondaryBorder: '#e5e5e5',
      secondaryHoverBg: '#f5f5f5',
      fontSize: '0.875rem',
      fontWeight: '500',
    },
    cards: {
      background: '#ffffff',
      border: '#f5f5f5',
      borderRadius: '0.5rem',
      borderWidth: '1px',
      shadow: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
      hoverShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)',
      padding: '1.5rem',
    },
    inputs: {
      background: '#ffffff',
      border: '#e5e5e5',
      borderRadius: '0.375rem',
      borderWidth: '1px',
      text: '#1a1a1a',
      placeholder: '#a3a3a3',
      focusBorder: '#3b82f6',
      focusShadow: '0 0 0 3px rgba(59, 130, 246, 0.1)',
    },
    badges: {
      borderRadius: '0.25rem',
      fontSize: '0.75rem',
      fontWeight: '500',
      padding: '0.25rem 0.5rem',
    },
    navigation: {
      background: '#ffffff',
      border: '#f5f5f5',
      itemColor: '#737373',
      itemHoverBg: '#f5f5f5',
      itemActiveBg: '#000000',
      itemActiveColor: '#ffffff',
    },
    layout: {
      pageBackground: '#fafafa',
      containerMaxWidth: '72rem',
      borderRadius: '0.5rem',
      spacing: '1.5rem',
    },
  },

  'modern': {
    id: 'modern',
    name: 'Modern',
    typography: {
      titleFont: 'system-ui, sans-serif',
      titleSize: '1.875rem',
      titleWeight: '700',
      titleColor: '#ffffff',
      bodyFont: 'system-ui, sans-serif',
      bodySize: '0.875rem',
      bodyWeight: '400',
      bodyColor: '#e5e5e5',
      mutedColor: '#a3a3a3',
      lineHeight: '1.5',
    },
    colors: {
      primary: '#3b82f6',
      primaryHover: '#2563eb',
      secondary: '#6b7280',
      secondaryHover: '#4b5563',
      accent: '#8b5cf6',
      accentHover: '#7c3aed',
      danger: '#ef4444',
      dangerHover: '#dc2626',
      success: '#10b981',
      successHover: '#059669',
      warning: '#f59e0b',
      warningHover: '#d97706',
      info: '#06b6d4',
      infoHover: '#0891b2',
    },
    buttons: {
      borderRadius: '0.5rem',
      borderWidth: '1px',
      primaryBg: '#3b82f6',
      primaryText: '#ffffff',
      primaryBorder: 'transparent',
      primaryHoverBg: '#2563eb',
      secondaryBg: '#27272a',
      secondaryText: '#e5e5e5',
      secondaryBorder: '#3f3f46',
      secondaryHoverBg: '#3f3f46',
      fontSize: '0.875rem',
      fontWeight: '500',
    },
    cards: {
      background: '#18181b',
      border: '#27272a',
      borderRadius: '0.75rem',
      borderWidth: '1px',
      shadow: '0 1px 3px 0 rgb(0 0 0 / 0.1)',
      hoverShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)',
      padding: '1.5rem',
    },
    inputs: {
      background: '#18181b',
      border: '#27272a',
      borderRadius: '0.5rem',
      borderWidth: '1px',
      text: '#e5e5e5',
      placeholder: '#71717a',
      focusBorder: '#3b82f6',
      focusShadow: '0 0 0 3px rgba(59, 130, 246, 0.1)',
    },
    badges: {
      borderRadius: '0.375rem',
      fontSize: '0.75rem',
      fontWeight: '500',
      padding: '0.25rem 0.5rem',
    },
    navigation: {
      background: '#18181b',
      border: '#27272a',
      itemColor: '#a1a1aa',
      itemHoverBg: '#27272a',
      itemActiveBg: '#3b82f6',
      itemActiveColor: '#ffffff',
    },
    layout: {
      pageBackground: '#0a0a0a',
      containerMaxWidth: '80rem',
      borderRadius: '0.5rem',
      spacing: '1.5rem',
    },
  },

  'tron': {
    id: 'tron',
    name: 'Tron',
    typography: {
      titleFont: '"Rajdhani", system-ui, sans-serif',
      titleSize: '2rem',
      titleWeight: '800',
      titleColor: '#00ffff',
      bodyFont: 'system-ui, sans-serif',
      bodySize: '0.875rem',
      bodyWeight: '400',
      bodyColor: '#e0e0ff',
      mutedColor: '#a0a0d0',
      lineHeight: '1.6',
    },
    colors: {
      primary: '#00ffff',
      primaryHover: '#00cccc',
      secondary: '#ff00ff',
      secondaryHover: '#cc00cc',
      accent: '#ffff00',
      accentHover: '#cccc00',
      danger: '#ff0066',
      dangerHover: '#cc0052',
      success: '#00ff88',
      successHover: '#00cc6e',
      warning: '#ff9900',
      warningHover: '#cc7a00',
      info: '#00ccff',
      infoHover: '#00a3cc',
    },
    buttons: {
      borderRadius: '0rem',
      borderWidth: '2px',
      primaryBg: 'transparent',
      primaryText: '#00ffff',
      primaryBorder: '#00ffff',
      primaryHoverBg: 'rgba(0, 255, 255, 0.1)',
      secondaryBg: 'transparent',
      secondaryText: '#ff00ff',
      secondaryBorder: '#ff00ff',
      secondaryHoverBg: 'rgba(255, 0, 255, 0.1)',
      fontSize: '0.875rem',
      fontWeight: '700',
    },
    cards: {
      background: '#0a0015',
      border: '#00ffff',
      borderRadius: '0rem',
      borderWidth: '2px',
      shadow: '0 0 20px rgba(0, 255, 255, 0.3)',
      hoverShadow: '0 0 30px rgba(0, 255, 255, 0.5)',
      padding: '1.5rem',
    },
    inputs: {
      background: '#0a0015',
      border: '#00ffff',
      borderRadius: '0rem',
      borderWidth: '2px',
      text: '#e0e0ff',
      placeholder: '#6060a0',
      focusBorder: '#ff00ff',
      focusShadow: '0 0 10px rgba(255, 0, 255, 0.5)',
    },
    badges: {
      borderRadius: '0rem',
      fontSize: '0.75rem',
      fontWeight: '700',
      padding: '0.25rem 0.75rem',
    },
    navigation: {
      background: '#0a0015',
      border: '#00ffff',
      itemColor: '#00ffff',
      itemHoverBg: 'rgba(0, 255, 255, 0.1)',
      itemActiveBg: 'rgba(0, 255, 255, 0.2)',
      itemActiveColor: '#00ffff',
    },
    layout: {
      pageBackground: '#000010',
      containerMaxWidth: '80rem',
      borderRadius: '0rem',
      spacing: '1.5rem',
    },
  },
}

export const getPresetNames = () => Object.keys(themePresets)

export const getPreset = (id: string): PlatformTheme | undefined => themePresets[id]

export const getAllPresets = (): PlatformTheme[] => Object.values(themePresets)
