/**
 * Next.js Fullstack App Workflow Template
 *
 * Standard process for building production-ready Next.js applications
 * with all quality gates and redundancy checks.
 */

import {
  WorkflowTemplate,
  STANDARD_QUALITY_GATES,
  PHASE_REDUNDANCY_REQUIREMENTS,
} from '../types';

export const NEXTJS_FULLSTACK_TEMPLATE: WorkflowTemplate = {
  id: 'nextjs_fullstack_app',
  name: 'Next.js Fullstack Application',
  description:
    'Complete workflow for building production-ready Next.js applications with API routes, database integration, and full quality assurance.',
  app_type: 'nextjs',
  estimated_duration_hours: 120, // 15 days with 8-hour workdays

  // Phases in order
  phases: [
    // PHASE 1: Requirements & Planning
    {
      phase: 'requirements',
      name: 'Requirements & Planning',
      description: 'Gather requirements, define scope, and plan architecture',
      order: 1,
      dependencies: [],
      quality_gates: [],
      task_templates: [
        {
          id: 'req_gather',
          title: 'Gather and document requirements',
          description:
            'Work with user to understand app goals, features, target audience, and technical constraints',
          type: 'analysis',
          required_capabilities: ['requirements_analysis', 'documentation'],
          preferred_agent_types: ['requirements_analyst'],
          requires_redundancy: false,
          estimated_hours: 8,
          acceptance_criteria: [
            'User stories documented',
            'Feature list prioritized',
            'Success metrics defined',
            'Technical constraints identified',
          ],
          quality_checks: ['Requirements completeness', 'Stakeholder approval'],
        },
        {
          id: 'req_review',
          title: 'Review requirements with system architect',
          description: 'System architect reviews requirements for technical feasibility',
          type: 'review',
          required_capabilities: ['system_design', 'architecture'],
          preferred_agent_types: ['system_architect'],
          requires_redundancy: true,
          redundancy_agent_types: ['requirements_analyst', 'system_architect'],
          estimated_hours: 4,
          acceptance_criteria: [
            'Requirements are technically feasible',
            'No conflicting requirements',
            'Architecture implications identified',
          ],
          quality_checks: ['Technical feasibility confirmed', 'Both agents approve'],
        },
      ],
    },

    // PHASE 2: Architecture Design
    {
      phase: 'architecture',
      name: 'Architecture Design',
      description: 'Design system architecture, database schema, and API structure',
      order: 2,
      dependencies: ['requirements'],
      quality_gates: [],
      task_templates: [
        {
          id: 'arch_design',
          title: 'Design system architecture',
          description:
            'Define tech stack, architecture patterns, data flow, and component structure',
          type: 'analysis',
          required_capabilities: ['system_design', 'architecture'],
          preferred_agent_types: ['system_architect'],
          requires_redundancy: false,
          estimated_hours: 12,
          acceptance_criteria: [
            'Architecture diagram created',
            'Tech stack decisions documented',
            'Data flow defined',
            'Deployment strategy outlined',
          ],
          quality_checks: ['Architecture is scalable', 'Follows best practices'],
        },
        {
          id: 'db_schema_design',
          title: 'Design database schema',
          description: 'Design database tables, relationships, and indexes',
          type: 'feature',
          required_capabilities: ['database_design', 'backend'],
          preferred_agent_types: ['backend_architect'],
          requires_redundancy: false,
          estimated_hours: 8,
          acceptance_criteria: [
            'Database schema documented',
            'Relationships defined',
            'Indexes identified',
            'Migration plan created',
          ],
          quality_checks: ['Schema is normalized', 'Performance considerations addressed'],
        },
        {
          id: 'api_design',
          title: 'Design API structure',
          description: 'Define API endpoints, request/response formats, and authentication',
          type: 'feature',
          required_capabilities: ['api_design', 'backend'],
          preferred_agent_types: ['backend_architect'],
          requires_redundancy: false,
          estimated_hours: 8,
          acceptance_criteria: [
            'API endpoints documented',
            'Request/response schemas defined',
            'Authentication strategy defined',
            'Error handling patterns established',
          ],
          quality_checks: ['API follows REST principles', 'Security considerations addressed'],
        },
        {
          id: 'arch_review',
          title: 'Architecture review (multi-agent)',
          description: 'Multiple architects review and approve the architecture',
          type: 'review',
          required_capabilities: ['architecture', 'system_design'],
          preferred_agent_types: ['system_architect', 'backend_architect', 'frontend_architect'],
          requires_redundancy: true,
          redundancy_agent_types: ['system_architect', 'backend_architect', 'frontend_architect'],
          estimated_hours: 4,
          acceptance_criteria: [
            'All architects approve',
            'No major concerns raised',
            'Architecture is well-documented',
          ],
          quality_checks: ['All agents approve', 'Documentation complete'],
        },
      ],
    },

    // PHASE 3: Development
    {
      phase: 'development',
      name: 'Development',
      description: 'Implement the application according to architecture',
      order: 3,
      dependencies: ['architecture'],
      quality_gates: [STANDARD_QUALITY_GATES.LINTING, STANDARD_QUALITY_GATES.TYPE_CHECKING],
      task_templates: [
        {
          id: 'dev_setup',
          title: 'Setup Next.js project with TypeScript',
          description:
            'Initialize Next.js project with TypeScript, ESLint, Prettier, and necessary dependencies',
          type: 'feature',
          required_capabilities: ['frontend', 'typescript'],
          preferred_agent_types: ['frontend_architect'],
          requires_redundancy: false,
          estimated_hours: 4,
          acceptance_criteria: [
            'Project initialized',
            'Dependencies installed',
            'Linting configured',
            'TypeScript configured',
          ],
          quality_checks: ['Build succeeds', 'No TypeScript errors'],
        },
        {
          id: 'db_setup',
          title: 'Setup database and migrations',
          description: 'Setup Supabase/database and create initial migration files',
          type: 'feature',
          required_capabilities: ['database', 'backend'],
          preferred_agent_types: ['backend_architect'],
          requires_redundancy: false,
          estimated_hours: 6,
          acceptance_criteria: [
            'Database connected',
            'Migrations created',
            'Migrations tested',
            'Seed data available',
          ],
          quality_checks: ['Migrations run successfully', 'Schema matches design'],
        },
        {
          id: 'api_routes',
          title: 'Implement API routes',
          description: 'Create Next.js API routes with validation and error handling',
          type: 'feature',
          required_capabilities: ['backend', 'api_development'],
          preferred_agent_types: ['backend_architect'],
          requires_redundancy: false,
          estimated_hours: 20,
          acceptance_criteria: [
            'All endpoints implemented',
            'Request validation added',
            'Error handling consistent',
            'Authentication integrated',
          ],
          quality_checks: ['All routes return correct status codes', 'Validation works'],
        },
        {
          id: 'ui_components',
          title: 'Build UI components',
          description: 'Create React components with TypeScript and Tailwind CSS',
          type: 'feature',
          required_capabilities: ['frontend', 'react', 'typescript'],
          preferred_agent_types: ['frontend_architect'],
          requires_redundancy: false,
          estimated_hours: 24,
          acceptance_criteria: [
            'All components built',
            'Components are typed',
            'Responsive design',
            'Accessibility considered',
          ],
          quality_checks: ['No TypeScript errors', 'Components render correctly'],
        },
        {
          id: 'integration',
          title: 'Integrate frontend with API',
          description: 'Connect frontend components to API routes with proper state management',
          type: 'feature',
          required_capabilities: ['frontend', 'backend', 'integration'],
          preferred_agent_types: ['frontend_architect', 'backend_architect'],
          requires_redundancy: false,
          estimated_hours: 16,
          acceptance_criteria: [
            'All API calls implemented',
            'Loading states handled',
            'Error states handled',
            'Success states handled',
          ],
          quality_checks: ['Data flows correctly', 'No console errors'],
        },
      ],
    },

    // PHASE 4: Security Review
    {
      phase: 'security',
      name: 'Security Review',
      description: 'Comprehensive security audit with redundancy',
      order: 4,
      dependencies: ['development'],
      quality_gates: [
        STANDARD_QUALITY_GATES.SECURITY_AUDIT,
        STANDARD_QUALITY_GATES.VULNERABILITY_SCAN,
        STANDARD_QUALITY_GATES.AUTH_REVIEW,
      ],
      task_templates: [
        {
          id: 'sec_audit',
          title: 'Security audit',
          description: 'Review code for security vulnerabilities (SQL injection, XSS, CSRF, etc.)',
          type: 'review',
          required_capabilities: ['security', 'code_review'],
          preferred_agent_types: ['security_engineer'],
          requires_redundancy: false,
          estimated_hours: 8,
          acceptance_criteria: [
            'No critical vulnerabilities',
            'Authentication secure',
            'Authorization properly implemented',
            'Input validation comprehensive',
          ],
          quality_checks: ['No critical issues', 'All medium issues addressed or tracked'],
        },
        {
          id: 'dep_scan',
          title: 'Dependency vulnerability scan',
          description: 'Scan all dependencies for known vulnerabilities',
          type: 'analysis',
          required_capabilities: ['security', 'devops'],
          preferred_agent_types: ['security_engineer'],
          requires_redundancy: false,
          estimated_hours: 2,
          acceptance_criteria: [
            'All dependencies scanned',
            'Vulnerable dependencies updated',
            'Exceptions documented',
          ],
          quality_checks: ['No high-severity vulnerabilities', 'Scan report generated'],
        },
        {
          id: 'sec_review_redundancy',
          title: 'Security review by system architect',
          description: 'Second security review by system architect for redundancy',
          type: 'review',
          required_capabilities: ['security', 'architecture'],
          preferred_agent_types: ['system_architect'],
          requires_redundancy: true,
          redundancy_agent_types: ['security_engineer', 'system_architect'],
          estimated_hours: 4,
          acceptance_criteria: [
            'System architect approves',
            'Architecture security validated',
            'No conflicting findings',
          ],
          quality_checks: ['Both agents approve', 'All concerns resolved'],
        },
      ],
    },

    // PHASE 5: Performance Optimization
    {
      phase: 'performance',
      name: 'Performance Optimization',
      description: 'Performance testing and optimization with redundancy',
      order: 5,
      dependencies: ['development'],
      quality_gates: [
        STANDARD_QUALITY_GATES.PERFORMANCE_BENCHMARK,
        STANDARD_QUALITY_GATES.BUNDLE_SIZE,
      ],
      task_templates: [
        {
          id: 'perf_audit',
          title: 'Performance audit',
          description: 'Measure and optimize performance (load time, bundle size, API latency)',
          type: 'analysis',
          required_capabilities: ['performance', 'optimization'],
          preferred_agent_types: ['performance_engineer'],
          requires_redundancy: false,
          estimated_hours: 8,
          acceptance_criteria: [
            'Lighthouse score > 90',
            'Bundle size < 200KB',
            'API response time < 200ms',
            'Optimizations applied',
          ],
          quality_checks: ['Meets performance targets', 'No performance regressions'],
        },
        {
          id: 'perf_review_redundancy',
          title: 'Performance review by system architect',
          description: 'Second performance review by system architect',
          type: 'review',
          required_capabilities: ['performance', 'architecture'],
          preferred_agent_types: ['system_architect'],
          requires_redundancy: true,
          redundancy_agent_types: ['performance_engineer', 'system_architect'],
          estimated_hours: 2,
          acceptance_criteria: [
            'System architect approves',
            'Performance meets standards',
          ],
          quality_checks: ['Both agents approve'],
        },
      ],
    },

    // PHASE 6: Testing
    {
      phase: 'testing',
      name: 'Testing',
      description: 'Comprehensive testing suite',
      order: 6,
      dependencies: ['development'],
      quality_gates: [
        STANDARD_QUALITY_GATES.UNIT_TEST_COVERAGE,
        STANDARD_QUALITY_GATES.INTEGRATION_TESTS,
        STANDARD_QUALITY_GATES.E2E_TESTS,
      ],
      task_templates: [
        {
          id: 'unit_tests',
          title: 'Write unit tests',
          description: 'Write unit tests for components and utilities (>80% coverage)',
          type: 'test',
          required_capabilities: ['testing', 'frontend'],
          preferred_agent_types: ['frontend_architect'],
          requires_redundancy: false,
          estimated_hours: 12,
          acceptance_criteria: [
            'Unit tests written',
            'Coverage > 80%',
            'All tests pass',
          ],
          quality_checks: ['Coverage threshold met', 'Tests are meaningful'],
        },
        {
          id: 'integration_tests',
          title: 'Write integration tests',
          description: 'Write integration tests for API routes',
          type: 'test',
          required_capabilities: ['testing', 'backend'],
          preferred_agent_types: ['backend_architect'],
          requires_redundancy: false,
          estimated_hours: 8,
          acceptance_criteria: [
            'Integration tests written',
            'All API routes tested',
            'All tests pass',
          ],
          quality_checks: ['All routes covered', 'Tests are comprehensive'],
        },
        {
          id: 'e2e_tests',
          title: 'Write E2E tests',
          description: 'Write end-to-end tests with Playwright or Cypress',
          type: 'test',
          required_capabilities: ['testing', 'e2e'],
          preferred_agent_types: ['frontend_architect'],
          requires_redundancy: false,
          estimated_hours: 10,
          acceptance_criteria: [
            'E2E tests written',
            'Critical user flows tested',
            'All tests pass',
          ],
          quality_checks: ['User flows covered', 'Tests are stable'],
        },
      ],
    },

    // PHASE 7: Documentation
    {
      phase: 'documentation',
      name: 'Documentation',
      description: 'Complete technical and user documentation',
      order: 7,
      dependencies: ['development', 'testing'],
      quality_gates: [
        STANDARD_QUALITY_GATES.API_DOCS,
        STANDARD_QUALITY_GATES.USER_DOCS,
        STANDARD_QUALITY_GATES.DEPLOYMENT_GUIDE,
      ],
      task_templates: [
        {
          id: 'api_docs',
          title: 'Write API documentation',
          description: 'Document all API endpoints with examples',
          type: 'docs',
          required_capabilities: ['documentation', 'technical_writing'],
          preferred_agent_types: ['technical_writer'],
          requires_redundancy: false,
          estimated_hours: 6,
          acceptance_criteria: [
            'All endpoints documented',
            'Examples provided',
            'Authentication explained',
          ],
          quality_checks: ['Documentation is clear', 'Examples work'],
        },
        {
          id: 'user_docs',
          title: 'Write user documentation',
          description: 'Write user guides and README',
          type: 'docs',
          required_capabilities: ['documentation', 'technical_writing'],
          preferred_agent_types: ['technical_writer'],
          requires_redundancy: false,
          estimated_hours: 6,
          acceptance_criteria: [
            'README complete',
            'User guide written',
            'Screenshots included',
          ],
          quality_checks: ['Documentation is beginner-friendly', 'Complete coverage'],
        },
        {
          id: 'deploy_docs',
          title: 'Write deployment guide',
          description: 'Document deployment process and configuration',
          type: 'docs',
          required_capabilities: ['documentation', 'devops'],
          preferred_agent_types: ['technical_writer', 'backend_architect'],
          requires_redundancy: false,
          estimated_hours: 4,
          acceptance_criteria: [
            'Deployment steps documented',
            'Environment variables listed',
            'Troubleshooting guide included',
          ],
          quality_checks: ['Guide is complete', 'Steps are tested'],
        },
      ],
    },

    // PHASE 8: Deployment Preparation
    {
      phase: 'deployment_prep',
      name: 'Deployment Preparation',
      description: 'Prepare for production deployment',
      order: 8,
      dependencies: ['security', 'performance', 'testing', 'documentation'],
      quality_gates: [
        STANDARD_QUALITY_GATES.BUILD_SUCCESS,
        STANDARD_QUALITY_GATES.DEPLOYMENT_CONFIG,
        STANDARD_QUALITY_GATES.ENV_VARS_CHECK,
      ],
      task_templates: [
        {
          id: 'deploy_config',
          title: 'Configure deployment',
          description: 'Setup deployment configuration (Vercel/Netlify/AWS)',
          type: 'feature',
          required_capabilities: ['devops', 'deployment'],
          preferred_agent_types: ['backend_architect'],
          requires_redundancy: false,
          estimated_hours: 4,
          acceptance_criteria: [
            'Deployment config created',
            'Environment variables set',
            'Build settings configured',
          ],
          quality_checks: ['Config is valid', 'Variables are secure'],
        },
        {
          id: 'prod_build',
          title: 'Test production build',
          description: 'Build and test production build locally',
          type: 'test',
          required_capabilities: ['devops', 'testing'],
          preferred_agent_types: ['backend_architect'],
          requires_redundancy: false,
          estimated_hours: 2,
          acceptance_criteria: [
            'Production build succeeds',
            'No build warnings',
            'App runs in production mode',
          ],
          quality_checks: ['Build is successful', 'No errors in production mode'],
        },
        {
          id: 'deploy_review_redundancy',
          title: 'Deployment review by system architect',
          description: 'System architect reviews deployment configuration',
          type: 'review',
          required_capabilities: ['architecture', 'devops'],
          preferred_agent_types: ['system_architect'],
          requires_redundancy: true,
          redundancy_agent_types: ['backend_architect', 'system_architect'],
          estimated_hours: 2,
          acceptance_criteria: [
            'System architect approves',
            'Deployment is production-ready',
          ],
          quality_checks: ['Both agents approve', 'All concerns resolved'],
        },
      ],
    },

    // PHASE 9: Final Review
    {
      phase: 'final_review',
      name: 'Final Review & Sign-off',
      description: 'Final multi-agent review before marketplace release',
      order: 9,
      dependencies: ['deployment_prep'],
      quality_gates: [],
      task_templates: [
        {
          id: 'final_review',
          title: 'Final multi-agent review',
          description: 'Multiple senior agents review the complete application',
          type: 'review',
          required_capabilities: ['architecture', 'security', 'performance'],
          preferred_agent_types: ['system_architect', 'security_engineer', 'performance_engineer'],
          requires_redundancy: true,
          redundancy_agent_types: ['system_architect', 'security_engineer', 'performance_engineer'],
          estimated_hours: 6,
          acceptance_criteria: [
            'All agents approve',
            'All quality gates passed',
            'No critical issues',
            'Ready for deployment',
          ],
          quality_checks: [
            'All 3 agents approve',
            'All quality gates green',
            'Deployment checklist complete',
          ],
        },
      ],
    },
  ],

  // Quality gates for this workflow
  quality_gates: [
    {
      id: STANDARD_QUALITY_GATES.LINTING,
      name: 'Linting Check',
      description: 'Code must pass ESLint with no errors',
      phase: 'development',
      required: true,
      criteria: [
        {
          id: 'lint_no_errors',
          name: 'No ESLint errors',
          description: 'npm run lint passes with 0 errors',
          check_type: 'automated',
          status: 'pending',
        },
      ],
      status: 'pending',
      checked_by_agent_ids: [],
    },
    {
      id: STANDARD_QUALITY_GATES.TYPE_CHECKING,
      name: 'TypeScript Type Checking',
      description: 'No TypeScript errors',
      phase: 'development',
      required: true,
      criteria: [
        {
          id: 'ts_no_errors',
          name: 'No TypeScript errors',
          description: 'tsc --noEmit passes with 0 errors',
          check_type: 'automated',
          status: 'pending',
        },
      ],
      status: 'pending',
      checked_by_agent_ids: [],
    },
    {
      id: STANDARD_QUALITY_GATES.SECURITY_AUDIT,
      name: 'Security Audit',
      description: 'Application passes security review',
      phase: 'security',
      required: true,
      criteria: [
        {
          id: 'no_critical_vulns',
          name: 'No critical vulnerabilities',
          description: 'Security review finds no critical issues',
          check_type: 'agent_review',
          status: 'pending',
        },
        {
          id: 'auth_secure',
          name: 'Authentication is secure',
          description: 'Authentication implementation is secure',
          check_type: 'agent_review',
          status: 'pending',
        },
      ],
      status: 'pending',
      checked_by_agent_ids: [],
    },
    {
      id: STANDARD_QUALITY_GATES.VULNERABILITY_SCAN,
      name: 'Dependency Vulnerability Scan',
      description: 'No high-severity vulnerabilities in dependencies',
      phase: 'security',
      required: true,
      criteria: [
        {
          id: 'no_high_severity_deps',
          name: 'No high-severity vulnerabilities',
          description: 'npm audit shows no high-severity issues',
          check_type: 'automated',
          status: 'pending',
        },
      ],
      status: 'pending',
      checked_by_agent_ids: [],
    },
    {
      id: STANDARD_QUALITY_GATES.PERFORMANCE_BENCHMARK,
      name: 'Performance Benchmark',
      description: 'Application meets performance targets',
      phase: 'performance',
      required: true,
      criteria: [
        {
          id: 'lighthouse_score',
          name: 'Lighthouse Score > 90',
          description: 'Lighthouse performance score above 90',
          check_type: 'automated',
          threshold: 90,
          status: 'pending',
        },
        {
          id: 'api_latency',
          name: 'API Response Time < 200ms',
          description: 'Average API response time under 200ms',
          check_type: 'automated',
          threshold: 200,
          status: 'pending',
        },
      ],
      status: 'pending',
      checked_by_agent_ids: [],
    },
    {
      id: STANDARD_QUALITY_GATES.UNIT_TEST_COVERAGE,
      name: 'Unit Test Coverage',
      description: 'Unit test coverage above 80%',
      phase: 'testing',
      required: true,
      criteria: [
        {
          id: 'coverage_threshold',
          name: 'Coverage > 80%',
          description: 'Test coverage above 80%',
          check_type: 'automated',
          threshold: 80,
          status: 'pending',
        },
      ],
      status: 'pending',
      checked_by_agent_ids: [],
    },
    {
      id: STANDARD_QUALITY_GATES.INTEGRATION_TESTS,
      name: 'Integration Tests',
      description: 'All integration tests pass',
      phase: 'testing',
      required: true,
      criteria: [
        {
          id: 'integration_pass',
          name: 'All integration tests pass',
          description: 'npm run test:integration passes',
          check_type: 'automated',
          status: 'pending',
        },
      ],
      status: 'pending',
      checked_by_agent_ids: [],
    },
    {
      id: STANDARD_QUALITY_GATES.E2E_TESTS,
      name: 'End-to-End Tests',
      description: 'All E2E tests pass',
      phase: 'testing',
      required: true,
      criteria: [
        {
          id: 'e2e_pass',
          name: 'All E2E tests pass',
          description: 'npm run test:e2e passes',
          check_type: 'automated',
          status: 'pending',
        },
      ],
      status: 'pending',
      checked_by_agent_ids: [],
    },
    {
      id: STANDARD_QUALITY_GATES.API_DOCS,
      name: 'API Documentation',
      description: 'API documentation is complete',
      phase: 'documentation',
      required: true,
      criteria: [
        {
          id: 'api_docs_complete',
          name: 'All endpoints documented',
          description: 'Every API endpoint has documentation',
          check_type: 'manual',
          status: 'pending',
        },
      ],
      status: 'pending',
      checked_by_agent_ids: [],
    },
    {
      id: STANDARD_QUALITY_GATES.BUILD_SUCCESS,
      name: 'Production Build Success',
      description: 'Production build completes without errors',
      phase: 'deployment_prep',
      required: true,
      criteria: [
        {
          id: 'build_passes',
          name: 'Build succeeds',
          description: 'npm run build completes successfully',
          check_type: 'automated',
          status: 'pending',
        },
      ],
      status: 'pending',
      checked_by_agent_ids: [],
    },
  ],

  // Redundancy requirements
  redundancy_requirements: Object.values(PHASE_REDUNDANCY_REQUIREMENTS).filter(
    (req) => req !== null
  ) as any,
};
